module.exports = {
  appId: 'io.aievolutionlabs.hermes',
  productName: 'Hermes AIEL',
  copyright: 'Copyright © 2026 AI Evolution Labs',
  icon: 'public/aievolutionlabs-icon-1024.png',
  directories: {
    output: 'release',
    buildResources: 'assets',
  },
  files: [
    'dist/client/**/*',
    'dist/server/**/*',
    'electron/main.cjs',
    'electron/preload.cjs',
    'electron/prod-server.cjs',
    'electron/server-bundle.cjs',
    'assets/**/*',
    'public/**/*',
    'package.json',
    '!**/puppeteer-extra-plugin-stealth/**/*',
    '!**/playwright-extra/**/*',
  ],
  npmArgs: ['--ignore-scripts'],
  nodeGypRebuild: false,
  mac: {
    category: 'public.app-category.business',
    target: [{ target: 'dmg', arch: ['arm64', 'x64'] }],
    darkModeSupport: true,
    hardenedRuntime: false,
    gatekeeperAssess: false,
  },
  dmg: {
    title: 'Hermes — AI Evolution Labs',
    iconSize: 96,
    contents: [
      { x: 130, y: 220 },
      { x: 410, y: 220, type: 'link', path: '/Applications' },
    ],
  },
  win: {
    target: [{ target: 'nsis', arch: ['x64'] }],
  },
  nsis: {
    oneClick: true,
    perMachine: false,
    allowToChangeInstallationDirectory: false,
    deleteAppDataOnUninstall: false,
    shortcutName: 'Hermes AIEL',
  },
  publish: {
    provider: 'github',
    owner: 'aievolutionpl',
    repo: 'hermes-aievolutionlaba',
    releaseType: 'release',
  },
  asar: false,
  compression: 'maximum',
}
